#!/bin/sh 

apt autoremove -y && apt autoclean && apt update -y
apt install -f -y
apt install \
  firmware-linux-free \
  firmware-linux-nonfree \
  vim \
  -y

exit 0

# vim:set ai et sts=2 sw=2 tw=0:
