#!/bin/sh
#

# package
apt autoremove -y && apt autoclean && apt update -y
apt install -f -y
apt install \
  xorg openbox obconf \
  ntfs-3g exfat-utils \
  pavucontrol pulseaudio pulseaudio-utils pnmixer \
  network-manager network-manager-gnome bluetooth bluez bluez-tools blueman nfs-common \
  synaptic terminator pcmanfm engrampa atril ristretto galculator gparted gtkhash mousepad firefox-esr \
  light-locker lightdm-gtk-greeter lightdm-gtk-greeter-settings \
  -y

exit 0

# vim:set ai et sts=2 sw=2 tw=0:
